### ISSUE TITLE
Update Java 8 LTS to Java 11 LTS

### ISSUE THREAD

**Issue by Alexander-Krause** [ExplorViz/explorviz-backend#102]
Oracle introduced some changes to the licensing of Java 8. As a result (and for other matters) I would like to update ExplorViz to the new LTS version 11, if the used Eclipse- and Gradle plugins (PMD etc.) are compatible with Java 11.

**Comment by lotzk** [comment]
ExplorViz does comply with Java 11 with only minor changes regarding the dependencies. However, there seems to be no alpine based Docker image of openjdk 11. The ExplorViz images based on `openjdk:11` (non-alpine) have a size of about 600MB to 700MB, which quite large compared to the currently used ~150MB compared (based on `openjdk:8-alpine`) . The increased image size in turn slows down the build and thus the api testing noticeably.

**Comment by Alexander-Krause** [comment]
https://hub.docker.com/r/adoptopenjdk/openjdk11/tags?page=1&name=jdk-11.0.4_11-alpine

Might be worth a shot (jdk-11.0.4_11-alpine - 194.92 MB)

**Comment by Alexander-Krause** [comment]
@lotzk Can you also try the "jdk-11.0.4_11-alpine-slim" image? It has a slightly smaller size.

**Comment by Alexander-Krause** [comment]
@lotzk Can you also try the base image `openjdk : 11-jre-slim` instead of a jdk version?

**Comment by lotzk** [comment]
JRE works but the resulting images still have each a size of approximately 240MB (as opposed to 280MB with the alpine based adoptjdk).

I opend the PR here https://github.com/ExplorViz/explorviz-backend/pull/119.

**Comment by Alexander-Krause** [comment]
Closed with #119
