### ISSUE TITLE
Fix Gradle Deprecations

### ISSUE THREAD

**Issue by Alexander-Krause** [ExplorViz/explorviz-backend#103]
We seem to use to-be deprecated (in version 6) features of Gradle. Refactor these features.

**Comment by lotzk** [comment]
The only deprecation warning im greeted with (using gradle version 5.6) is

```Internal API constructor TaskReportContainer(Class<T>, Task) has been deprecated. This is scheduled to be removed in Gradle 6.0.```

This is due the older SpotBugs version we are using and can be resolved by upgrading to a newer version. I've opened a PR on this, see https://github.com/ExplorViz/explorviz-backend/pull/117.
