### ISSUE TITLE
Unique id handling

### ISSUE THREAD

**Issue by Alexander-Krause** [ExplorViz/explorviz-backend#23]
The backend creates unique IDs for every entity at the moment. However, future work includes different extensions that will create entities in the frontend and save them via HTTP. Therefore, IDs must be initially created in the frontend. This introduces bugs, if two entities with the same id and type are stored in the Ember Store.

We require a way to handle these situations. Possible approaches (maybe not applicable) are:

- Frontend requests unique ID via a entity scaffold, e.g., landscape that contains nothing but the unique id. Then use this scaffold to save the to-be saved entity.
- Use type string for the id. To-be saved entities have a id with the prefix `to-be-generated-by-backend-X`, where `X` is a counter variable used in the frontend.
- More?

**Comment by Alexander-Krause** [comment]
New idea for this problem: State a String as partial prefix for a service in its configuration file, e.g. `landscape` for a landscape service.

Implement a HTTP web service in the explorviz-backend that acts as counter for services. On startup, a service requests its unique service id from this service and uses is as second part for the prefix, e.g. `landscape-1`. Entities then use the prefix and an internal counter for their id, e.g., `landscape-1-1`, `landscape-1-2` etc.

The format looks like this: `servicePrefix-serviceUniqueID-entityUniqueID`

**Comment by Alexander-Krause** [comment]
### Backend

New idea, again. The approach above seems to be too complicated due to concurrent access on the file from multiple services. Instead, use [a Redis Key-Value store as counter](https://redis.io/commands/incr#pattern-counter).

The `incr` operation is atomic and should also return the updated value. Therefore, no synchronization is necessary. Use [Jedis](https://github.com/xetorthio/jedis) as Redis Java client and implement a common `Redis connection client` in the shared package.

**Comment by lotzk** [comment]
Done with aeb7da314da2a12611f176bbb0995a4dd6ca027e
