### ISSUE TITLE
Inter service communication

### ISSUE THREAD

**Issue by Alexander-Krause** [ExplorViz/explorviz-backend#25]
Frontend uses JWT-based authentication / authorization for requests. Token generation is based on username and password validation. 

How should microservices communicate among each other?

**Comment by lotzk** [comment]
An approach to solving this, is to have the microservices provide additional interfaces with the required functionality. These interfaces mustn't be secured by JWT but only be accessible from within the system (the docker container) and unreachable from the outside (the API gateway). This allows internal communication between microservices without the need for a token or authorization at all.

**Comment by Alexander-Krause** [comment]
Sounds good. We should create a minimal test sample to verify this.

**Comment by Alexander-Krause** [comment]
New approach based on internal discussions: Use some kind of message broker, e.g., Kafka, RabbitMQ,..., for inter service communication

**Comment by Alexander-Krause** [comment]
**Done** Landscape services writes new landscapes to Kafka topic and any service can read these landscape and "subscribe" to new events. Also updated in the dummy project. 

User services etc. can also use this scheme.
