### ISSUE TITLE
Tests for auth service

### ISSUE THREAD

**Issue by Alexander-Krause** [ExplorViz/explorviz-backend#30]
We need well documented tests for this service, since future students should take these as starting point for their tests.

**Comment by lotzk** [comment]
Closed as of 4885ce30f0b82f51d374700a76598fea4ee8fdb1

**Comment by czirkelbach** [comment]
Refactor due to Morphia usage and TravisCI MongoDB container

**Comment by Alexander-Krause** [comment]
`dev-1` branch now contains the Morphia-based MongoDB refactoring. Tests can now be refactored.

**Comment by lotzk** [comment]
Fixed the tests. As agreed, they are now expecting a running MongoDB server and will fail if no connection can be established.
