### ISSUE TITLE
User role's descriptor null

### ISSUE THREAD

**Issue by dan0x09** [ExplorViz/explorviz-backend#36]
When creating a user or changing their properties, the following error is sent to the frontend:

`{"errors": [ { "status": "400", "title": "Error", "detail": "Unknown role: {1, null}" } ]}`

This happens due to the newly introduced check, whether the role is actually valid or not. However, the check is not the issue.
The role's descriptor is `null` and not `admin`. The problem seems to be that the frontend, when sending a request including a role, never sends a role's descriptor - only the id as in the following:

```
attributes: {username: "rolf2", password: null}
id: "4"
relationships: {roles: {data: [{type: "role", id: "1"}]}}
type: "user"
```

That probably results in the Role constructor being called with a descriptor that is `null`.

The `id` sent by the frontend should, however, be enough. IMO, it should be the backend's job to request the corresponding descriptor from the database and set the role object's descriptor accordingly.

**Comment by Alexander-Krause** [comment]
Missing data is due to this issue: https://github.com/ExplorViz/explorviz-frontend/issues/37

We can probably write a custom deserializer for this that fetches the right role by id on deseralization.

**Comment by Alexander-Krause** [comment]
@dan0x09 Can you verify if the latest commit fixes these problems?

**Comment by dan0x09** [comment]
@Alexander-Krause Works fine!
