### ISSUE TITLE
Use String instead of long for Trace Id

### ISSUE THREAD

**Issue by Malte-Hansen** [ExplorViz/explorviz-backend#42]
A long in java is a 64bit signed integer, the max safe integer is roughly 2^63. In Javascript the max safe integer is roughly 2^53, thus those data types are not matching. For most variables of type long which are sent to the frontend this is no issue in practice because most long variables are incremented step by step - never reaching a number as big as 2^53.

However, trace IDs are generated by the Kieker framework as opposed to the ExplorViz Backend. Since Kieker should handle a lot of incoming traces from different sources, the IDs are not simply incremented. It exists a function in Kieker which maps incoming traces to a variable of type long. This function uses all 64 bits to practically avoid collisions of IDs and thus returns usually an integer which is larger than 2^53.

As a result trace IDs are not interpreted correctly by the frontend and result in colliding trace IDs. To fix this issue we need to either map the big trace IDs to smaller traceIDs in the backend or use a string representation for the trace IDs. The latter is to be preferred, since mapping would be more compute intense and error prone than converting to a string.

**Comment by czirkelbach** [comment]
Fixed in branch dev-1.
