### ISSUE TITLE
Insufficient memory

### ISSUE THREAD

**Issue by lotzk** [ExplorViz/explorviz-backend#46]
Rarely, when running the explorviz application along with the frontend and the [Kieker Sample Application](https://github.com/czirkelbach/kiekerSampleApplication), the landscape service crashes due to insufficient memory. 

Error message:

```
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 241696768 bytes for committing reserved memory.
# An error report file with more information is saved as:
```

Relevant specs:
```
OS: Linux
RAM: 8GB
Java: openjdk version "1.8.0_202"
```

I can't find a reliable way to reproduce this behavior.

**Comment by lotzk** [comment]
This bug also occurs randomly when running the tests for the landscape service. Free memory is sufficient on the system.

**Comment by Alexander-Krause** [comment]
Closing this issue, since it did not occur once again.
