### ISSUE TITLE
Inject and Config annotation should be used in coexistence at constructor level

### ISSUE THREAD

**Issue by Alexander-Krause** [ExplorViz/explorviz-backend#58]
At the moment, our custom config annotation does not resolve properties, if used at constructor level with an Inject annotation for injecting non-config related DI-based services. 

We require this to optimally unit test classes, since property level injection is error prone. Sure, we could use the InjectMocks annotation of Mockito, but why should we write all this, if a simple constructor-only based DI could solve this and is furthermore the better way to achieve the same behavior.

**Comment by Alexander-Krause** [comment]
Done.

**Comment by Alexander-Krause** [comment]
I am thinking about banning the Config annotation from field level due to unwanted side effects for example in testing. @lotzk do you know any loc that will break due to this change?

**Comment by lotzk** [comment]
I found that the field level `@Config` annotation is still used in the several places (only regarding current dev-1), including the following

- History-Service
  - `MongoReplayJsonApiRepository`
  - `MongoLandscapeJsonApiRepository`
- Landscape-Service
  - `KafkaProducerFactory`
  - `SetupApplicationListener`
- User-Service
  - `DatastoreFactory`
  - `TestDatastoreFactory`
  - `Token-Service`

**Comment by Alexander-Krause** [comment]
Ok thank you. The `SetupApplicationListener`s must use the Config annotation at field level. Maybe we can implement a PMD rule to check this during development and use the `//NOPMD` comment if necessary, e.g., in the `SetupApplicationListener`.

**Comment by Alexander-Krause** [comment]
I am closing this issue in favor of a new title. Remaining `Config` annotations that can be refactored to Constructor-level will be refactored in passing.
