### ISSUE TITLE
Failing exchange under heavy-load between landscape service and frontend

### ISSUE THREAD

**Issue by Alexander-Krause** [ExplorViz/explorviz-backend#69]
At the moment, the landscape service uses SSE (server side events) to broadcast the latest landscape every tenth second to any subscribed frontend.

If under heavy load, the landscape service cannot satisfy the "tenth second" update. Therefore, it catches up after a short time, which results in multiple SSE to the frontend. The frontend cannot handle this and eventually crashes.

We need to fix this.

Additionally: Is there any better way to achieve an authorized exchange (publish / subscribe) between these two?

**Comment by lotzk** [comment]
Can you give additional information what you mean with "heavy load"? I see the problem but I can not reproduce it with the current sample app for monitoring.

**Comment by Alexander-Krause** [comment]
@lotzk had the idea to outsource the frontend-update functionality into a new service. I like this approach and will start to implement this.

**Comment by Alexander-Krause** [comment]
TODO: Test new broadcast-service. If fixed, close this issue.
