### ISSUE TITLE
Dummy Landscape cannot be drawn in frontend

### ISSUE THREAD

**Issue by dan0x09** [ExplorViz/explorviz-backend#72]
Currently, the dummy landscape delivered by the backend landscape service cannot be drawn by the KLAY layouter.

The error message given by the console:
![error_landscape_backend](https://user-images.githubusercontent.com/17865498/57525734-ca84ce80-732b-11e9-82cd-6dcf7c785784.png)

Both the kieker sample application and the dummy landscape included in the frontend's dummy mode work fine. However, it is to say that the kieker sample application does not have any communication lines to be drawn in landscape view.
Although I, at the moment, can't say what's the actual cause, investigating the [LandscapeDummyCreator](https://github.com/ExplorViz/explorviz-backend/blob/dev-1/landscape-service/src/main/java/net/explorviz/landscape/repository/LandscapeDummyCreator.java) for possible errors might be a good starting point.

**Comment by czirkelbach** [comment]
The generation of the dummy landscape gets removed in the next weeks.

**Comment by czirkelbach** [comment]
Solved through PR https://github.com/ExplorViz/explorviz-backend/pull/91.
