### ISSUE TITLE
POST requests with invalid JSON-API types result in 500 status codes

### ISSUE THREAD

**Issue by lotzk** [ExplorViz/explorviz-backend#73]
Any POST request to an enpoint that accepts JSON-API as data will return a 500 (Internal Server Error) status code, if the JSON-API type does not match the type the method expects. This is not expected behaviour, a status code 400 (Bad Request) should be returned instead.

This can be reproduces for example by posting the following (mind the type field) to `/v1/user/`:

```json
{
	"data": {
		"type": "userz",
		"attributes": {
			"username": "username",
			"password": "pw"
		}
	}
}
```

As far as I can tell this affects all endpoints that answers POST requests.

**Comment by Alexander-Krause** [comment]
Merged
