### ISSUE TITLE
Batch user request

### ISSUE THREAD

**Issue by Alexander-Krause** [ExplorViz/explorviz-backend#76]
At the moment, we use the `/users/batch` endpoint (as shown in [here](https://github.com/ExplorViz/explorviz-backend/blob/dev-1/user-service/src/main/java/net/explorviz/security/server/resources/UserResource.java#L127)) to allow clients, e.g., the frontend, to create multiple users via a user list.

Therefore, the frontend needs to create records and save them. This is not nice.

We should use `/users/batch` to introduce a sub resource class of the encompassing `UserResource` that is responsible for batch creation of users. Instead of a list of users we should additionally introduce a new class for example `BatchUserRequest` that contains the necessary data for the backend to fulfill the batch request.

`BatchUserRequest` might contain:

- Prefix for usernames, e.g., `experiment-1`
- Number of users to be created
- Roles that these users should inherit

**Comment by Alexander-Krause** [comment]
@lotzk We also require (the same) `user-preferences` for the to-be created users. Can `UserBatchRequest` be updated by a `user-preference` reference that is then copied for all new users?

**Comment by lotzk** [comment]
> Can UserBatchRequest be extended with a user-preference reference that is then copied (with a new Id) for all new users

With the new implementation of the settings-service, the user-service does not handle settings anymore. We would need to enable some kind of communication between both services to implement this feature. If we use Kafka, this would require additional work on the settings-service.

**Comment by lotzk** [comment]
This feature has been merged (https://github.com/ExplorViz/explorviz-backend/pull/77).
