### ISSUE TITLE
Limit Jersey filter scope

### ISSUE THREAD

**Issue by Alexander-Krause** [ExplorViz/explorviz-backend#83]
When applied, our authentication and authorization filters are used in any resource class, i.e., any endpoint that a client contacts.

I would like to limit their scope by using the @NameBinding [annotation](https://stackoverflow.com/questions/23641345/jersey-request-filter-only-on-certain-uri). This will enable us to finely choose which resource class should use these filters (probably every resource class) and which new (upcoming) filters should also be applied.

TODO

- Check how order of filters can be manipulated, e.g., resource class X should use the filter order 3,2,1 whereas resource class Y should use the order 1,2,3.

**Comment by Alexander-Krause** [comment]
@lotzk can be closed?

**Comment by lotzk** [comment]
Close with https://github.com/ExplorViz/explorviz-backend-shared/pull/12. 

The named binding has no impact on the order in which the filters are executed. Make sure to register the filters in the correct order.
