### ISSUE TITLE
Unused Jetty Server in Landscape Service

### ISSUE THREAD

**Issue by lotzk** [ExplorViz/explorviz-backend#89]
With #60 all HTTP resource for accessing landscapes and associated entities have been outsourced into the history service. Despite not providing any HTTP endpoints anymore, the landscape service still runs on top of Jersey. This unnecessary dependency should be removed.

**Comment by Alexander-Krause** [comment]
@lotzk You already did that, right?

**Comment by lotzk** [comment]
Yes I did that, but it requires some changes in the shared project, see https://github.com/ExplorViz/explorviz-backend-shared/pull/7. The PR is still open since we were unsure how to handle failing config injections.

**Comment by lotzk** [comment]
Closed with https://github.com/ExplorViz/explorviz-backend/pull/96
