### ISSUE TITLE
Permissions: Role-based resource authorization

### ISSUE THREAD

**Issue by czirkelbach** [ExplorViz/explorviz-backend#92]
We should enhance the resource authorization via `@RolesAllowed` to use centralized roles and not check for strings like `user`.

**Comment by Alexander-Krause** [comment]
What is the advantage of using mode classes for roles here? What additional data is included in potential role classes? What is the effect for JSON-API? 

Let's discuss this first, because at the moment I do not see advantages, but more coupling.

**Comment by Alexander-Krause** [comment]
@czirkelbach and I talked about this today. We should use a class that contains constant string values for the roles, so that typos etc. cannot happen.

https://stackoverflow.com/a/3272859

**Comment by Alexander-Krause** [comment]
Role refactoring by @lotzk was (mostly, still a few bugs) applied to backend in 15b03eddf4dc06779599cb582a2e722dee9d5b8d and 706488a5a414cc049fb1b6b7116f056a4ec0afbb.
