### ISSUE TITLE
History-service: Jesery Unit Test for LandscapeResoruce failing

### ISSUE THREAD

**Issue by czirkelbach** [ExplorViz/explorviz-backend#93]
In the history-service the Jesery unit test for the `LandscapeResource` is failing due to the intregrated uploading functionality which uses a `MultiPart`.

Currently bypassed to successfully run the build in `history-service/build.gradle`:

```
// ignore the tests until it the endpoint test is fixed
test {
	ignoreFailures = true
}
```

**Comment by Alexander-Krause** [comment]
Fixed in 77ca12b44d6c9acddf82e51ec5c86ba7253084d8
