### ISSUE TITLE
Provide resource classes for every model type

### ISSUE THREAD

**Issue by Alexander-Krause** [ExplorViz/explorviz-backend#97]
At the moment, we obtain the landscape in a single request with all belonging data already included in the payload. There are times, where we only require a sub model of the landscape etc.

Therefore, we should provide resource classes for every model type in the history-service. We need to discuss the following points:

- How should we persist a single instance of a type, e.g. an instance for a node (still stringified or is the overhead for parsing [Mongo -> Java -> JSON-API] negligible?

**Comment by lotzk** [comment]
I'm in the process of providing resources for each type contained in landscapes. However, I'm unsure to which extend subtypes qualify to be served as a stand-alone resource.

The current type hierarchy of a landscape is roughly the following:

- `Landscape`
  - `Timestamp`
  - `Event`
    - `ApplicationCommunication[]`
  - `System`
    - `NodeGroups[]`
      - `Nodes[]`
        - `Application[]`
          - `Component []`
            - `Clazz[]`
        - `DBQueries[]`
        - `AppCommunication[]`
        - `AggregatedClazzCommunication[]`
        - `AggregatedClazzCommunication[]`
        - `Trace[]`
    
For instance, should resources be provided for types as deep as `Clazz` or just to the `Application` level?

**Comment by lotzk** [comment]
Closing this for now since we plan to replace the REST API with GraphQL in near future.
